// <auto-generated />
namespace medEvolution.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OrdenExamenExamenDetalle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrdenExamenExamenDetalle));
        
        string IMigrationMetadata.Id
        {
            get { return "201811050525582_OrdenExamen-Examen-Detalle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
